### ISSUE TITLE
Rename "ViewController.swift"

### ISSUE THREAD

**Issue by capnsolo** [ciauri/undeadbread#4]
Use a more descriptive name.

**Comment by rue-calvin** [comment]
Or at least be consistent. `ViewController.swift`, `ViewControllerA.swift`, `ViewControllerB.swift`, etc.

**Comment by ciauri** [comment]
I like to obfuscate my viewcontroller names to prevent h4xxorz from reverse engineering my binaries.

TODO: Rename VC's to follow pattern: `"\(UUID())".swift`
